
name: Test Dotfiles on Manjaro

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dotfiles-test:
    name: ${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["manjarolinux/base:latest"]
    container:
      image: ${{ matrix.container }}
      env:
        USER: dev
        HOME: /home/dev
        CHEZMOI_VERBOSE: 1
    steps:
      - name: Prepare environment
        run: |
          sudo pacman -Syu --noconfirm sudo chezmoi git

      - name: chezmoi init dotfiles
        run: |
          sudo useradd -m dev || true
          sudo -u dev chezmoi init --apply collieiscute -v
