
name: Test Dotfiles on Manjaro and Arch

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dotfiles-test:
    name: ${{ matrix.container }}-test
    runs-on: ubuntu-latest
    continue-on-error: ture
    strategy:
      matrix:
        container: ["manjarolinux/base:latest", "archlinux/archlinux"]
    container:
      image: ${{ matrix.container }}
      env:
        USER: dev
        HOME: /home/dev
        CHEZMOI_VERBOSE: 1
    steps:
      - name: Prepare environment
        run: |
          if command -v sudo >/dev/null; then
            sudo pacman -Syu --noconfirm sudo chezmoi git
            sudo useradd -m dev || true
            echo "dev ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/dev
          else
            pacman -Syu --noconfirm sudo chezmoi git
            useradd -m dev || true
            echo "dev ALL=(ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/dev
          fi

      - name: chezmoi init dotfiles
        run: |
          sudo -u dev chezmoi init --apply collieiscute -v
